// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqGKFHBT7-xDVEquiKwKkcuXOkuTqa9E',
    appId: '1:1027716689465:android:635181d8eab856245b67e8',
    messagingSenderId: '1027716689465',
    projectId: 't-save-project',
    storageBucket: 't-save-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfpIZHOKuj1aMELxcov-lRojnngtslwY',
    appId: '1:1027716689465:ios:85a04cd5fdd91d035b67e8',
    messagingSenderId: '1027716689465',
    projectId: 't-save-project',
    storageBucket: 't-save-project.appspot.com',
    androidClientId: '1027716689465-ogb8m9k7llr6dp2blohrhqjdn7d5epdi.apps.googleusercontent.com',
    iosClientId: '1027716689465-ee6ql5f0ersphp7jkgd243tleq58co95.apps.googleusercontent.com',
    iosBundleId: 'com.tsaveuser.www',
  );
}
